version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev:
        patterns:
          - "aiointercept"
          - "prek"
          - "pytest"
          - "pytest-*"
          - "ruff"
          - "ty"
    ignore:
      - dependency-name: "setuptools"
      - dependency-name: "tomli"
      - dependency-name: "twine"
      - dependency-name: "typing-extensions"
      - dependency-name: "wheel"
      - dependency-name: "aiohttp"
      - dependency-name: "orjson"
      - dependency-name: "yarl"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ci:
        patterns: ["*"]

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pre-commit:
        patterns: ["*"]
