repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.16
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/NSPBot911/ty-pre-commit
    rev: v0.0.44
    hooks:
      - id: ty-check
        args:
          - --python=venv
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args:
          - --skip="./.*"
          - --quiet-level=2
        exclude_types: [csv, json]
  - repo: builtin
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args:
          - --branch=main
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: pretty-format-json
        args:
          - --no-sort-keys
        exclude: "Pipfile.lock"
