name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    name: Release Drafter
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
